### ISSUE TITLE
testNumericFilter in ClientTest class fail

### ISSUE THREAD

**Issue by manuelcugliari** [RedisLabs/JRediSearch#1]
Hi,
    when i run ClientTest in the imported mvn project testNumericFilter fails. Here the stacktrace:

redis.clients.jedis.exceptions.JedisDataException: Invalid numeric filter

	at redis.clients.jedis.Protocol.processError(Protocol.java:128)
	at redis.clients.jedis.Protocol.process(Protocol.java:162)
	at redis.clients.jedis.Protocol.read(Protocol.java:216)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:310)
	at redis.clients.jedis.Connection.getRawObjectMultiBulkReply(Connection.java:276)
	at redis.clients.jedis.Connection.getObjectMultiBulkReply(Connection.java:281)
	at io.redisearch.client.Client.search(Client.java:125)
	at io.redisearch.client.ClientTest.testNumericFilter(ClientTest.java:83)

Thanks,
Manuel

**Comment by dvirsky** [comment]
Are you sure you have:
1. Redis 4.0 RC2 running on port 6379
2. The RediSearch module loaded in it?

**Comment by manuelcugliari** [comment]
I install the branch "unstable".

127.0.0.1:6379> INFO
# Server
redis_version:999.999.999

Is it correct?

**Comment by manuelcugliari** [comment]
I install the branch "unstable".

127.0.0.1:6379> INFO
# Server
redis_version:999.999.999

Is it correct?

**Comment by manuelcugliari** [comment]
I install the branch "unstable".

127.0.0.1:6379> INFO
redis_version:999.999.999

Is it correct?

**Comment by manuelcugliari** [comment]
Ok I install Redis 4.0 RC2 (running on port 6379). ClientTest gives same error.

**Comment by dvirsky** [comment]
Did you install the module? See http://redisearch.io getting started

**Comment by manuelcugliari** [comment]
Yes, and I start redis with --loadmodule module.so

**Comment by dvirsky** [comment]
Works properly now AFAIK. Closing
